# Generated by Django 4.2.7 on 2023-11-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_created_by_user_created_date_user_modified_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
    ]
