# Generated by Django 4.2.7 on 2023-11-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_user_created_date_remove_user_modified_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
