# Generated by Django 4.2.7 on 2023-11-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('course_description', models.TextField()),
                ('course_date', models.DateField()),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
