# Generated by Django 4.2.7 on 2023-12-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_for_admins_course_for_examiners_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='for_admins',
        ),
        migrations.RemoveField(
            model_name='course',
            name='for_examiners',
        ),
        migrations.RemoveField(
            model_name='course',
            name='for_students',
        ),
    ]
